version: '3'
services: 
  api:
    image: httpstestdockerimage
    ports:
    - "8080:80"
    - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+443;http://+80"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 